<!--page header / breadcrumbs-->
<section class="breadcrumbs">
    <div class="container">
        <div class="page-header">
            <div class="row">
                <div class="span8">
                    <h1>Equipe <small>/ Pesquisa e Desenvolvimento</small></h1>
                    <div><a href="#" controller="index" action="inicio" onclick="Layout.go($(this))" >Home</a> &nbsp;&rsaquo;&nbsp; Equipe</div>
                </div>
                <div class="span4 hidden-phone">
                    <section class="search clearfix">
                        <form id="search" class="input-append">
                            <input class="span4" id="appendedInputButton" size="16" type="text" placeholder="Buscar por informações de membros" />
                            <input class="btn search-bt" type="submit" name="submit" value="" />
                        </form>
                    </section>
                </div>
            </div>
        </div>
    </div>
</section>

<!--container-->
<section id="container">
    <div class="container">
        <div class="row">
            <div class="span12">
                <div class="row member-info">
                    <div class="span3" align="center">
                         <img  src="./public/images/professoradamo.jpg" />
                            <h3 class="member-name">Ádamo Santana</h3>
                            <p class="member-possition">Coordenador</p>
                            <p class="member-social"><a target="_blank" href="http://lattes.cnpq.br/4073088744952858"><img style=" height: 18px; width: 24px" src="./public/images/logolattes.gif"></a><a href="mailto:alwkynew@gmail.com"><i class="icon-envelope"></i></a></p>
                    </div>
                    <div class="span3" align="center">
                        <img alt="" src="./public/images/andrea.jpg" height="60"/>
                        <h3 class="member-name">Andreia Lopes</h3>
                        <p class="member-possition">Bolsista</p>
                        <p class="member-social"><a target="_blank" href="http://lattes.cnpq.br/6058206442603055"><img style=" height: 18px; width: 24px" src="./public/images/logolattes.gif"></a><a href="mailto:andreia.lopes@itec.ufpa.br"><i class="icon-envelope"></i></a></p>
                    </div>
                    <div class="span3" align="center">
                        <img alt="" src="./public/images/jacob.jpg" height="60"/>
                        <h3 class="member-name">Antonio Jacob Jr.</h3>
                        <p class="member-possition">Colaborador</p>
                        <p class="member-social"><a target="_blank" href="http://lattes.cnpq.br/4510520291728075"><img style=" height: 18px; width: 24px" src="./public/images/logolattes.gif"></a><a href="mailto:jacobjr@ufpa.br"><i class="icon-envelope"></i></a></p>
                    </div>
                    <div class="span3" align="center">
                        <img alt="" src="./public/images/carlos.jpg" height="60"/>
                        <h3 class="member-name">Carlos Assunção</h3>
                        <p class="member-possition">Bolsista</p>
                        <p class="member-social"><a target="_blank" href="http://lattes.cnpq.br/1470239160589861"><img style=" height: 18px; width: 24px" src="./public/images/logolattes.gif"></a><a href="mailto:jrcarlos.ga@hotmail.com"><i class="icon-envelope"></i></a></p>
                    </div>
                    <div class="span3" align="center">
                        <img alt="" src="./public/images/renatofrances.jpg" height="60"/>
                        <h3 class="member-name">Carlos Renato Francês</h3>
                        <p class="member-possition">Pesquisador</p>
                        <p class="member-social"><a target="_blank" href="http://lattes.cnpq.br/7458287841862567"><img style=" height: 18px; width: 24px" src="./public/images/logolattes.gif"></a><a href="mailto:rfrances@ufpa.br"><i class="icon-envelope"></i></a></p>
                    </div>
                    <div class="span3" align="center">
                        <img alt="" src="./public/images/claudio.jpg" height="60"/>
                        <h3 class="member-name">Cláudio da Rocha</h3>
                        <p class="member-possition">Pesquisador</p>
                        <p class="member-social"><a target="_blank" href="http://lattes.cnpq.br/5422287933944134"><img style=" height: 18px; width: 24px" src="./public/images/logolattes.gif"></a><a href="mailto:claudioalex.rocha@gmail.com"><i class="icon-envelope"></i></a></p>
                    </div>
                    <div class="span3" align="center">
                        <img alt="" src="./public/images/diego.jpg" height="60"/>
                        <h3 class="member-name">Diego Cardoso</h3>
                        <p class="member-possition">Pesquisador</p>
                        <p class="member-social"><a target="_blank" href="http://lattes.cnpq.br/0507944343674734"><img style=" height: 18px; width: 24px" src="./public/images/logolattes.gif"></a><a href="mailto:diego@ufpa.br"><i class="icon-envelope"></i></a></p>
                    </div>
                    <div class="span3" align="center">
                        <img alt="" src="./public/images/edinaldo.jpg" height="60"/>
                        <h3 class="member-name">Edinaldo dos Santos</h3>
                        <p class="member-possition">Bolsista</p>
                        <p class="member-social"><a target="_blank" href="http://lattes.cnpq.br/5073645108691562"><img style=" height: 18px; width: 24px" src="./public/images/logolattes.gif"></a><a href="mailto:edinaldoluisdossantos@gmail.com"><i class="icon-envelope"></i></a></p>
                    </div>
                    <div class="span3" align="center">
                        <img alt="" src="./public/images/emily.jpg" height="60"/>
                        <h3 class="member-name">Emily Araújo</h3>
                        <p class="member-possition">Bolsista</p>
                        <p class="member-social"><a target="_blank" href="http://lattes.cnpq.br/4994853546866474"><img style=" height: 18px; width: 24px" src="./public/images/logolattes.gif"></a><a href="mailto:emilyv.araujo@gmail.com"><i class="icon-envelope"></i></a></p>
                    </div>
                    <div class="span3" align="center">
                        <img alt="" src="./public/images/fabio.jpg" height="60"/>
                        <h3 class="member-name">Fábio Lobato</h3>
                        <p class="member-possition">Doutorado</p>
                        <p class="member-social"><a target="_blank" href="http://lattes.cnpq.br/8320014491229434"><img style=" height: 18px; width: 24px" src="./public/images/logolattes.gif"></a><a href="mailto:lobato.fabiof@gmail.com"><i class="icon-envelope"></i></a></p>
                    </div>
                    <div class="span3" align="center">
                        <img alt="" src="./public/images/gilberto.jpg" height="60"/>
                        <h3 class="member-name">Gilberto Nerino Jr. </h3>
                        <p class="member-possition">Doutorado</p>
                        <p class="member-social"><a target="_blank" href="http://lattes.cnpq.br/8391942175575646"><img style=" height: 18px; width: 24px" src="./public/images/logolattes.gif"></a><a href="mailto:gilbertonerinojr@gmail.com"><i class="icon-envelope"></i></a></p>
                    </div>
                    <div class="span3" align="center">
                        <img alt="" src="./public/images/iago.jpg" height="60"/>
                        <h3 class="member-name">Iago Cavalcante</h3>
                        <p class="member-possition">Bolsista</p>
                        <p class="member-social"><a target="_blank" href="http://lattes.cnpq.br/5824536737794839"><img style=" height: 18px; width: 24px" src="./public/images/logolattes.gif"></a><a href="mailto:iagoangelimc@gmail.com"><i class="icon-envelope"></i></a></p>
                    </div>
                    <div class="span3" align="center">
                        <img alt="" src="./public/images/igor.jpg" height="60"/>
                        <h3 class="member-name">Igor Araújo</h3>
                        <p class="member-possition">Bolsista</p>
                        <p class="member-social"><a target="_blank" href="http://lattes.cnpq.br/6459556275938592"><img style=" height: 18px; width: 24px" src="./public/images/logolattes.gif"></a><a href="mailto:igor.araujo92@gmail.com"><i class="icon-envelope"></i></a></p>
                    </div>
                    <div class="span3" align="center">
                        <img alt="" src="./public/images/italo.jpg" height="60"/>
                        <h3 class="member-name">Ítalo Flexa Di Paolo</h3>
                        <p class="member-possition">Doutorado</p>
                        <p class="member-social"><a target="_blank" href="http://lattes.cnpq.br/7195767161641034"><img style=" height: 18px; width: 24px" src="./public/images/logolattes.gif"></a><a href="mailto:itflexa@gmail.com"><i class="icon-envelope"></i></a></p>
                    </div>
 		    <div class="span3" align="center">
                           <img  src="./public/images/joaogabriel.jpg" />
                            <h3 class="member-name">João Gabriel Lima</h3>
                            <p class="member-possition">Mestrado</p>
                            <p class="member-social"><a target="_blank" href="http://lattes.cnpq.br/7905157737895005"><img style=" height: 18px; width: 24px" src="./public/images/logolattes.gif"></a></p>
                    </div>
                    <div class="span3" align="center">
                        <img alt="" src="./public/images/liviane.jpg" height="60"/>
                        <h3 class="member-name">Liviane Ponte Rego</h3>
                        <p class="member-possition">Doutorado</p>
                        <p class="member-social"><a target="_blank" href="http://lattes.cnpq.br/3119189681371475"><img style=" height: 18px; width: 24px" src="./public/images/logolattes.gif"></a><a href="mailto:luizcf14@gmail.com"><i class="icon-envelope"></i></a></p>
                    </div>
                    <div class="span3" align="center">
                        <img alt="" src="./public/images/luiz.jpg" height="60"/>
                        <h3 class="member-name">Luiz Ferreira Neto</h3>
                        <p class="member-possition">Bolsista</p>
                        <p class="member-social"><a target="_blank" href="http://lattes.cnpq.br/4267138767629286"><img style=" height: 18px; width: 24px" src="./public/images/logolattes.gif"></a><a href="mailto:livika@gmail.com"><i class="icon-envelope"></i></a></p>
                    </div>
                    <div class="span3" align="center">
                        <img alt="" src="./public/images/marcelino.jpg" height="60"/>
                        <h3 class="member-name">Marcelino da Silva</h3>
                        <p class="member-possition">Coordenador</p>
                        <p class="member-social"><a target="_blank" href="http://lattes.cnpq.br/7080513172499497"><img style=" height: 18px; width: 24px" src="./public/images/logolattes.gif"></a><a href="mailto:marcelino@ufpa.br"><i class="icon-envelope"></i></a></p>
                    </div>
                    <div class="span3" align="center">
                        <img alt="" src="./public/images/marcia.jpg" height="60"/>
                        <h3 class="member-name">Márcia Pinheiro</h3>
                        <p class="member-possition">Mestrado</p>
                        <p class="member-social"><a target="_blank" href="http://lattes.cnpq.br/9402892997548187"><img style=" height: 18px; width: 24px" src="./public/images/logolattes.gif"></a><a href="mailto:eng.marciafontes@gmail.com"><i class="icon-envelope"></i></a></p>
                    </div>
                    <div class="span3" align="center">
                        <img alt="" src="./public/images/marcus.jpg" height="60"/>
                        <h3 class="member-name">Marcus Vinicius Dias</h3>
                        <p class="member-possition">Bolsista</p>
                        <p class="member-social"><a target="_blank" href="http://lattes.cnpq.br/8844636780873262"><img style=" height: 18px; width: 24px" src="./public/images/logolattes.gif"></a><a href="mailto:vmarcusv@gmail.com"><i class="icon-envelope"></i></a></p>
                    </div>
                    <div class="span3" align="center">
                        <img alt="" src="./public/images/marissa.jpg" height="60"/>
                        <h3 class="member-name">Marissa Carvalho</h3>
                        <p class="member-possition">Bolsista</p>
                        <p class="member-social"><a target="_blank" href="http://lattes.cnpq.br/2668825548689669"><img style=" height: 18px; width: 24px" src="./public/images/logolattes.gif"></a><a href="mailto:marissa.brasil@gmail.com"><i class="icon-envelope"></i></a></</p>
                    </div>
                    <div class="span3" align="center">
                        <img alt="" src="./public/images/vincent.jpg" height="60"/>
                        <h3 class="member-name">Vincent Tadaiesky </h3>
                        <p class="member-possition">Mestrado</p>
                        <p class="member-social"><a target="_blank" href="http://lattes.cnpq.br/5559524842947867"><img style=" height: 18px; width: 24px" src="./public/images/logolattes.gif"></a><a href="mailto:vincentwillian@gmail.com"><i class="icon-envelope"></i></a></p>
                    </div>
                </div>
            </div>
        </div>
        <hr>
        <div class="page-header">
            <div class="row">
                <div class="span8">
                    <h1>Alumni <small></small></h1>
                </div>
                
            </div>
        </div>
        <div class="row" style="margin-top: 30px">
            <div class="span12">
                <div class="row member-info">
                    <div class="span3" align="center">
                           <img  src="./public/images/arilene.jpg" />
                            <h3 class="member-name">Arilene França</h3>
                            <p class="member-possition">Mestra</p>
                            <p class="member-social"><a target="_blank" href="http://lattes.cnpq.br/6665410111833245"><img style=" height: 18px; width: 24px" src="./public/images/logolattes.gif"></a></p>
                    </div>
                       <div class="span3" align="center">
                        <img alt="" src="./public/images/carlosdiego.jpg"/>
                        <h3 class="member-name">Carlos Diego Damasceno</h3>
                        <p class="member-possition">Iniciação Científica</p>
                        <p class="member-social"><a target="_blank" href="http://lattes.cnpq.br/2329667585098950"><img style=" height: 18px; width: 24px" src="./public/images/logolattes.gif"></a></p>
                    </div>
                    <div class="span3" align="center">
                        <img alt="" src="./public/images/elton.jpg"/>
                        <h3 class="member-name">Elton Moutinho</h3>
                        <p class="member-possition">Iniciação Científica</p>
                        <p class="member-social"><a target="_blank" href="http://lattes.cnpq.br/1543349110651243"><img style=" height: 18px; width: 24px" src="./public/images/logolattes.gif"></a></p>
                    </div>
                    <div class="span3" align="center">
                        <img alt="" src="./public/images/ivan.jpg"/>
                        <h3 class="member-name">Ivan Oliveira</h3>
                        <p class="member-possition">Iniciação Científica</p>
                        <p class="member-social"><a target="_blank" href="http://lattes.cnpq.br/0679005353327280"><img style=" height: 18px; width: 24px" src="./public/images/logolattes.gif"></a></p>
                    </div>
                   
                    <div class="span3" align="center">
                        <img alt="" src="./public/images/lilian.jpg"/>
                        <h3 class="member-name">Lilian Dias</h3>
                        <p class="member-possition">Mestra</p>
                        <p class="member-social"><a target="_blank" href="http://lattes.cnpq.br/0212800890257958"><img style=" height: 18px; width: 24px" src="./public/images/logolattes.gif"></a></p>
                    </div>
                   
                </div>
            </div>
        </div>
        <hr />
        <div class="row">
            <section id="page" class="pull-left span12">
                
                <div class="row">
                    <div class="span12">
                        
                        <blockquote class="pull-right" align="right">
                            <p>”Greatness from small beginnings."</p>
                            <small>Sir Francis Drake</small>
                        </blockquote>
                    </div>
                </div>
              
            <!--    <h2>Nossas vagas disponíveis <small></small></h2>
                <div class="row">
                    <div class="span12">
                        <div class="media">
                            <div class="media-body">
                                <h4 class="media-heading">
                                    <a href="javascript:;">
                                        Desenvolvimento de Sistemas Software
                                    </a>
                                </h4>
                                <p>Cras sit amet arcu ante, sed adipiscing nibh quisque vitae turpis sit amet dui condimentum</p>
                            </div>
                        </div>
                    </div>
                </div> -->
                <hr />
                <div class="row">
                    <div class="span12">
                        <h2>Parceiros <small></small></h2>
                        <span class="span3">
                            <blockquote align="center">
                                <a href="http://www.lprad.ufpa.br/" target="_blank">
                                    <h4>LPRAD - Laboratório de Planejamento de Redes de Alto Desempenho</h4>
                                </a>
                            </blockquote>
                        </span>
                        <span class="span3" >
                            <blockquote align="center">
                                <a href="http://www.lea.ufpa.br/" target="_blank">
                                    <h4>LEA - Laboratório de Eletromagnetismo Aplicado</h4>
                                    <br/>
                                </a>
                            </blockquote>
                        </span>
                        <span class="span3">
                            <blockquote align="center">
                                <a href="https://www.laps.ufpa.br/" target="_blank">
                                    <h4>LAPS - Laboratório de Processamento de Sinais</h4>
                                    <br/>
                                </a>
                            </blockquote>
                        </span>
                    </div>
                </div>
            </section>
        </div>
    </div>
</section>
