<link href="./public/css/bs-preview.css" type="text/css" rel="stylesheet"/>
<!--page header / breadcrumbs-->
<section class="breadcrumbs">
    <div class="container">
            <div class="row">
                <div class="span8">
                    <section id="apps">
                    <div class="page-header">
                        <h1>Início</h1>
                        <div><a href="#" controller="index" action="inicio" onclick="Layout.go($(this))" >Home</a></div> 
                    </div>
                   
                    <br/>
                    <p>O Laboratório de Inteligência Computacional e Pesquisa Operacional (LINC) 
                        é associado à Faculdade de Engenharia da Computação e Telecomunicações (FCT) 
                        do Instituto de Tecnologia (ITEC) da Universidade Federal do Pará (UFPA). <br/>
                        O LINC tem como objetivo gerar soluções e avanços, motivados pelo problemas 
                        e aplicações do “mundo real”, na pesquisa e implementação de modelos matemáticos, 
                        estatísticos e de inteligência computacional para a geração de conhecimento. <br/>
                        O LINC atua acerca de duas principais áreas: </p>
                    <ul>
                        <li>Investigar novos modelos, bem como aprimoramentos, para sistemas e algoritmos, nas áreas de matemática, otimização e inteligência computacional; 
                        </li>
                        <li>Prover logística para o meio público e profissional, através do desenvolvimento de sistemas e metodologias para suporte à decisão,
                            permitindo, particularmente, identificar padrões, realizar predições e inferir cenários e comportamentos para análise e diagnóstico.
                        </li>
                    </ul>        
                        Dentre os domínios recentes de trabalho estão: telecomunicações, agroindústria, energia, saúde e segurança.
                        <br>
                        <br>
                </section> 
                       
                
                </div>
                <div class="span4 hidden-phone">
                    <section class="search clearfix">
                        <form id="search" class="input-append">
                            <input class="span4" id="appendedInputButton" size="16" type="text" placeholder="Buscar por informações" />
                            <input class="btn search-bt" type="submit" name="submit" value="" />
                        </form>
                    </section>
                </div>
                <div class="span3 bs-docs-sidebar">
                 <h3>Últimas Notícias</h3>
                    <ul class="nav nav-list bs-docs-sidenav">                        
                        <li>
                            <a href="#" controller="index" action="noticias" onclick="Layout.go($(this))" >
                              <div style="width: 10%; float: left; text-align: center; margin-right: 10%">
                                04<br>
                                MAR
                              </div>
                              <div style="width: 80%">
                                Universidade de Leipzig e UFPA...<i class="icon-chevron-right"></i>
                              </div>
                            </a>
                        </li>
                        <li style="background-color: rgb(4,110,149);">
                            <a style="color: antiquewhite;" href="#" controller="index" action="noticias" onclick="Layout.go($(this))" >
                              <div style="width: 10%; float: left; text-align: center; margin-right: 10%">
                                19<br>
                                JUN
                              </div>
                              <div style="width: 80%">
                                Lançamento do novo site do Mobile Qualis
                                <i class="icon-chevron-right"></i>
                              </div>
                            </a>
                        </li>
                        <li>
                            <a href="#" controller="index" action="noticias" onclick="Layout.go($(this))" >
                              <div style="width: 10%; float: left; text-align: center; margin-right: 10%">
                                25<br>
                                MAR
                              </div>
                              <div style="width: 80%">
                                Apresentação do projeto de extensão intitulado Fábrica de Games<i class="icon-chevron-right"></i>
                              </div>
                            </a>
                        </li> 
                        <li>
                            <a href="#" controller="index" action="noticias" onclick="Layout.go($(this))" >
                              <div style="width: 10%; float: left; text-align: center; margin-right: 10%">
                                19<br>
                                MAR
                              </div>
                              <div style="width: 80%">
                               Fábrica de Games: capacitação e criação...<i class="icon-chevron-right"></i>
                              </div>
                            </a>
                        </li>                        
                        <li>
                            <a href="#" controller="index" action="noticias" onclick="Layout.go($(this))" >
                              <div style="width: 10%; float: left; text-align: center; margin-right: 10%">
                                04<br>
                                MAR
                              </div>
                              <div style="width: 80%">
                                Chamada de Estágio de Iniciação Científica...<i class="icon-chevron-right"></i>
                              </div>
                            </a>
                        </li>
                </ul>
                 <p style="margin-top: 20px;"><a href="#" controller="index" action="noticias" class="btn btn-large btn-welcome" onclick="Layout.go($(this))">
                     Mostrar Todos<i class="icon-chevron-right"></i></a></p>
                <br>
                <br>
                <br>
            </div>
            </div>
    </div>
</section>
<!--
<section id="container">
    <div class="container">
        <div class="row">  
            <div class="span9">
                 Dropdowns 
               <section id="apps">
                    <div class="page-header">
                        <h1>Início</h1>
                    </div>
                   
                    <br/>
                    <p>O Laboratório de Inteligência Computacional e Pesquisa Operacional (LINC) 
                        é associado à Faculdade de Engenharia da Computação e Telecomunicações (FCT) 
                        do Instituto de Tecnologia (ITEC) da Universidade Federal do Pará (UFPA). <br/>
                        O LINC tem como objetivo gerar soluções e avanços, motivados pelo problemas 
                        e aplicações do “mundo real”, na pesquisa e implementação de modelos matemáticos, 
                        estatísticos e de inteligência computacional para a geração de conhecimento. <br/>
                        O LINC atua acerca de duas principais áreas: </p>
                    <ul>
                        <li>Investigar novos modelos, bem como aprimoramentos, para sistemas e algoritmos, nas áreas de matemática, otimização e inteligência computacional; 
                        </li>
                        <li>Prover logística para o meio público e profissional, através do desenvolvimento de sistemas e metodologias para suporte à decisão,
                            permitindo, particularmente, identificar padrões, realizar predições e inferir cenários e comportamentos para análise e diagnóstico.
                        </li>
                    </ul>        
                        Dentre os domínios recentes de trabalho estão: telecomunicações, agroindústria, energia, saúde e segurança.
                
                    <h2>{{App name}}</h2>
                    <div class="bs-docs-example">
                        {{app_images}}
                    </div>
                    <pre class="prettyprint linenums">
                        {{app_description}}
                    </pre>
                </section> -->
                <!-- Button Groups -->
               <!-- ================================================== 
               <section id="galeria">
                    <div class="page-header">
                        <h1>Galeria</h1>
                    </div>
                    <br/>
                    <p>Registros fotográficos de nossos encintros, reuniões, confraternizações e outros momentos importantes que desejamos compartilhar com todos.</p>
                    <div class="row">
                        <div class="span12 our-works"><h4>{{galeria_nome}}</h4></div>
                        <div class="span9">
                            <div id="our-projects" class="carousel bttop">
                                <div class="carousel-wrapper">
                                    <ul class="portfolio">
                                        <li>
                                            <article>
                                                <div class="inner-image">
                                                    <a href="./public/example/view.jpg" data-rel="prettyPhoto">
                                                        <img src="./public/example/latest1.jpg" alt=""/>
                                                        <span class="frame-overlay"></span>
                                                    </a>
                                                </div>
                                                <div class="sliding">
                                                    <div class="inner-text">
                                                        <p>{{descricao}}</p>
                                                    </div>
                                                </div>
                                            </article>
                                        </li>

                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>

                </section> -->

                <!-- Split button dropdowns
                ================================================== --> 
          <!--     <section id="videos">
                    <div class="page-header">
                        <h1>Vídeos</h1>
                    </div>
                        <br/>
                    <p>Nossos vídeos incluem campanhas institucionais, vídeo-aulas, tutoriais e externos que são de interesse por compartilharem nossas linhas de pesquisa.</p>
                    <div class="row">
                        <div class="span12 our-works"><h4>{{galeria_video_nome}}</h4></div>
                        <div class="span9">
                            <div id="framevideos" class="carousel bttop">
                                <div class="carousel-wrapper">
                                    <ul class="portfolio">
                                        <li>
                                            <article>
                                                <div class="inner-image">
                                                    <a href="./public/example/view.jpg" data-rel="prettyPhoto">
                                                        <img src="./public/example/latest1.jpg" alt=""/>
                                                        <span class="frame-overlay"></span>
                                                    </a>
                                                </div>
                                                <div class="sliding">
                                                    <div class="inner-text">
                                                        <p>{{descricao}}</p>
                                                    </div>
                                                </div>
                                            </article>
                                        </li>

                                    </ul>
                                </div>
                            </div>

                        </div>
                    </div>
                </section> 



            </div>
            
        </div>

    </div>
</section> -->
<script type="text/javascript">
    $(document).ready(function(){
        $('#framevideos').elastislide({
            imageW : 270,
            border : 0,
            minItems : 1,
            margin : 30
        });
        $('#our-projects').elastislide({
            imageW : 270,
            border : 0,
            minItems : 1,
            margin : 30
        });
    });
    
</script>