<!--page header / breadcrumbs-->
<section class="breadcrumbs">
    <div class="container">
        <div class="page-header">
            <div class="row">
                <div class="span8">
                    <h1>Mapa do site <small>/ Localize mais rapidamente o que deseja</small></h1>
                    <div><a href="#" controller="index" action="inicio" onclick="Layout.go($(this))" >Home</a> &nbsp;&rsaquo;&nbsp; Mapa do site</div>
                </div>
            </div>
        </div>
    </div>
</section>

<!--container-->
<section id="container">
    <div class="container">
        <div class="row">
            <div class="span8">

                <ul>
                    <li><a href="javascript:;" controller="index" action="inicio" onclick="Layout.go($(this))">
                            <span class="name" >Home</span>
                        </a>
                    </li>
                    <li><a href="javascript:;" controller="index" action="pesquisa" onclick="Layout.go($(this))"><span class="name">Pesquisa</span></a>
                        <ul>
                            <li><a href="javascript:;">Linhas de Pesquisa</a></li>
                            <li><a href="javascript:;">Projetos</a></li>
                            <li><a href="javascript:;">Publicações</a></li>
                            <li><a href="javascript:;">Áreas de Interesse</a></li>
                            <li><a href="javascript:;">Programa de Afiliados</a>
                                <ul>
                                    <li><a href="javascript:;">Acesso à visualização de informações do projeto</a></li>
                                    <li><a href="javascript:;">Acompanhamento de atividades</a></li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                    <li><a href="javascript:;" controller="index" action="media" onclick="Layout.go($(this))"><span class="name">Mídia</span></a>
                        <ul>
                            <li><a href="javascript:;">Códigos/Apps</a></li>
                            <li><a href="javascript:;">Galeria</a></li>
                            <li><a href="javascript:;">Videos</a></li>
                            <li><a href="javascript:;">Livros</a></li>
                            <li><a href="javascript:;">Logos/Templates</a></li>
                        </ul>
                    </li>
                    <li><a href="javascript:;" controller="index" action="equipe" onclick="Layout.go($(this))"><span class="name" >Equipe</span></a></li>
                    <li><a href="javascript:;" controller="index" action="noticias" onclick="Layout.go($(this))"><span class="name">Notícias</span></a></li>
                    <li><a href="javascript:;" controller="index" action="servicos" onclick="Layout.go($(this))"><span class="name">Serviços</span></a></li>
                    <li><a href="javascript:;" controller="index" action="contato" onclick="Layout.go($(this))"><span class="name">Contato</span></a></li>
                </ul>
            </div>
        </div>
    </div>
</section>
