<!--page header / breadcrumbs-->
<section class="breadcrumbs">
    <div class="container">
        <div class="page-header">
            <div class="row">
                <div class="span8">
                    <h1>Notícias <small></small></h1>
                    <div><a href="#" controller="index" action="inicio" onclick="Layout.go($(this))" >Home</a> &nbsp;&rsaquo;&nbsp; Notícias</div>
                </div>
                <div class="span4 hidden-phone">
                    <section class="search clearfix">
                        <form id="search" class="input-append">
                            <input class="span4" id="appendedInputButton" size="16" type="text" placeholder="Buscar por notícias" />
                            <input class="btn search-bt" type="submit" name="submit" value="" />
                        </form>
                    </section>
                </div>
            </div>
        </div>
    </div>
</section>
<section id="container">
    <div class="container">
        <div class="row">
            <section id="page-sidebar" class="pull-left span12">
                <article class="blog-post">
                    <div class="row">
                        <div class="span1">
                            <div class="post-meta-day">04</div>
                            <div class="post-meta-month">Mar</div>
                        </div>
                        <div class="span11">
                            <h3 class="post-title"><a href="#">Chamada de Estágio de Iniciação Científica - PIBIC.</a></h3>
                            <ul class="post-meta">
                                <li>
                                <li><i class="icon-list-alt"></i> <a href="#">desenvolvimento</a></li>
                                <li><i class="icon-tag"></i> <a href="#">Trabalhe conosco</a> <a href="#">linc</a>
                                <li><i class="icon-comment"></i> <a href="#"></a></li>
                            </ul>
                            <div class="post-content">
                                <p>Modelagem e implementação de técnicas inteligentes para imputação múltipla no tratamento de dados ausentes. </p>
								<p>Pré-Requisitos: Proficiência em Java e C++; Conhecimentos em Algoritmos e Estruturas de Dados; Noções em Inteligência Computacional e Algoritmos Bioinspirados.</p>
								<p>Cursos: Ciência da Computação, Engenharia da Computação e Sistema de Informação, a partir do 4º semestre.</p>
								<p>Valor da bolsa: R$ 400,00.</p>
								<p>Os interessados devem mandar seu currículo para o email: lobato.fabio@ufpa.br, com o seguinte assunto: Vaga de Iniciação Científica.</p>
								<p><a href="http://www.fct.ufpa.br/files/bolsas/Chamada_PIBIC2.pdf" target="_blank" class="btn btn-large btn-welcome"><i class="icon-chevron-right"></i>Banner de Divulgação</a></p>
                            </div>
                        </div>
                    </div>
                </article>
            </section>
		</div>
		<hr/>
        <div class="row">
            <section id="page-sidebar" class="pull-left span6">
                <article class="blog-post">
                    <div class="row">
                        <div class="span1">
                            <div class="post-meta-day">24</div>
                            <div class="post-meta-month">Abr</div>
                        </div>
                        <div class="span5">
                            <h3 class="post-title"><a href="#">Mobile Qualis.</a></h3>
                            <ul class="post-meta">
                                <li>
                                <li><i class="icon-list-alt"></i> <a href="#">desenvolvimento</a></li>
                                <li><i class="icon-tag"></i> <a href="#">projeto</a> <a href="#">linc</a>
                                <li><i class="icon-comment"></i> <a href="#"></a></li>
                            </ul>
                            <div class="post-content">
                                <p>
                                    Mobile Qualis (MQ) é a identificação da aplicação, atualmente em sua versão 1.0, disponibilizada
									para uso em dispositivos móveis com sistema Android. Desenvolvida por membros do LINC, em conjunto
									com o Programa de Pós-Graduação em Engenharia Elétrica (PPGEE/UFPA), a app objetiva propiciar um
									acesso otimizado ao conteúdo do Qualis CAPES, difundindo o acesso e estendendo as funcionalidades
									já dispostas no Sistema WebQualis.
                                <p><a href="http://www.linc.ufpa.br/mobilequalis.apk" target="_blank" class="btn btn-large btn-welcome"><i class="icon-chevron-right"></i>Baixar o App</a></p>
								<div class="span3" align="center">
                                    <a href="http://www.linc.ufpa.br/mobilequalis.apk" target="_blank"><img  src="./public/images/mobile_qualis.png" /></a>
                                </div>
                                </p>
                            </div>
                        </div>
                    </div>
                </article>
            </section>
			<section id="page-sidebar" class="pull-left span6">
                <article class="blog-post">
                    <div class="row">
                        <div class="span1">
                            <div class="post-meta-day">07</div>
                            <div class="post-meta-month">Maio</div>
                        </div>
                        <div class="span5">
                            <h3 class="post-title"><a href="#">  Palestra prof. Vladimiro Miranda (INESCTEC-Porto).</a></h3>
                            <ul class="post-meta">
                              <li><i class="icon-list-alt"></i> <a href="#">palestra</a></li>
                                <li><i class="icon-tag"></i> <a href="#">INESCTEC-Porto</a>
                                <li><i class="icon-comment"></i> <a href="#"></a></li>
                            </ul>
                            <div class="post-content">
                                <p>
                                    O Prof. Dr. Vladimiro Miranda do Instituto de Engenharia de Sistemas e Computadores do Porto, 
                                    Portugal, ministrou a palestra no tema de <b>"MODELOS INTELIGENTES E DENSIFICAÇÃO DE DADOS".</b>
                                    A palestra foi realizado no auditório do Laboratório de Genética Humana e Médica da UFPA, sendo
                                    voltada também para novas aplicações nas áreas de Biologia, Medicina e Genética.</p>
                                    <div class="span3" align="center">
                                         <img  src="./public/images/prof.jpg" />
                                    </div>
                                <br/>
                            </div>
                        </div>
                    </div>
                </article>
            </section>
        </div>
        <hr/>
        <div class="row">
            <section id="page-sidebar" class="pull-left span6">
                <article class="blog-post">
                    <div class="row">
                        <div class="span1">
                            <div class="post-meta-day">28</div>
                            <div class="post-meta-month">Abr</div>
                        </div>
                        <div class="span5">
                            <h3 class="post-title"><a href="#"> XLVI Simpósio Brasileiro de Pesquisa Operacional.</a></h3>
                            <ul class="post-meta">
                              <li><i class="icon-list-alt"></i> <a href="#">sbpo</a></li>
                                <li><i class="icon-tag"></i> <a href="#">deadline</a>
                                <li><i class="icon-comment"></i> <a href="#"></a></li>
                            </ul>
                            <div class="post-content">
                                <p>
                                    
                                    XLVI Simpósio Brasileiro de Pesquisa Operacional será realizado em Salvador de 16 a 19 de setembro de 2014 e tem como tema oficial a "Pesquisa Operacional na Gestão da Segurança Pública”.<br>
                                    <b> Deadlines:</b>
                                    Prazo para submissão de trabalhos completos, propostas de minicursos, trabalhos de iniciação cientifica: até 30 de abril de 2014.<br>
                                    Prazo para envio de posters: até 30 de junho de 2014. </p>
                                <p><a href="http://www.sbpo2014.org/" target="_blank" class="btn btn-large btn-welcome"><i class="icon-chevron-right"></i>Continuar lendo</a></p>
                            </div>
                        </div>
                    </div>
                </article>
            </section>
            <section id="page-sidebar" class="pull-left span6">
                <article class="blog-post">
                    <div class="row">
                        <div class="span1">
                            <div class="post-meta-day">24</div>
                            <div class="post-meta-month">Abr</div>
                        </div>
                        <div class="span5">
                            <h3 class="post-title"><a href="#">III Workshop de Ciência e Tecnologia & Arte da Amazônia - WCTA 2014.</a></h3>
                            <ul class="post-meta">
                                <li><i class="icon-list-alt"></i> <a href="#">wcta</a></li>
                                <li><i class="icon-tag"></i> <a href="#">artigos</a> <a href="#">linc</a> <a href="#">lprad</a></li>
                                <li><i class="icon-comment"></i> <a href="#"></a></li>
                            </ul>
                            <div class="post-content">
                                <p>
                                    Nos dias 07 a 11 de abril, ocorreu o III Workshop de Ciência e Tecnologia & Arte da Amazônia 
                                    - WCTA 2014 na Universidade da Amazônia - UNAMA. 
                                    Com o intuito de promover a apresentação de conferências, palestras, oficinas e 
                                    mini-cursos de diferentes áreas do conhecimento, seguindo a tendência do 
                                    desenvolvimento da multidisciplinaridade das áreas, além da produção e divulgação de informações 
                                    e conhecimentos técnicos, científicos, tecnológicos e artísticos referentes às atividades ligadas à 
                                    Ciência e Tecnologia & Artes visando a melhoria do ambiente e da qualidade de vida 
                                    do homem da Amazônia. No houve as seguintes publicações: <i> Aplicativo Móvel Lúdico para Ensino de Alunos do nível Médio em Programação de Computadores. </i>
									<i> Programação de Computadores a Jovens do Ensino Médio. </i>
									<i>Protótipo para Ensino da Leitura e Escrita para Crianças com Dificuldades de Aprendizado.</i>
                                 </p>
        
                                <p><a href="http://www.unama.br/wcta/" target="_blank" class="btn btn-large btn-welcome"><i class="icon-chevron-right"></i>Continuar lendo</a></p>
                            </div>
                        </div>
                    </div>
                </article>
            </section>
            <hr />
        </div>
    </div>
</section>
