<!--page header / breadcrumbs-->
<section class="breadcrumbs">
    <div class="container">
        <div class="page-header">
            <div class="row">
                <div class="span8">
                    <h1>Pesquisa <small></small></h1>
                    <div><a href="#" controller="index" action="inicio" onclick="Layout.go($(this))" >Home</a> &nbsp;&rsaquo;&nbsp; Pesquisa</div>
                </div>
                <div class="span4 hidden-phone">
                    <section class="search clearfix">
                        <form id="search" class="input-append">
                            <input class="span4" id="appendedInputButton" size="16" type="text" placeholder="Buscar por projetos" />
                            <input class="btn search-bt" type="submit" name="submit" value="" />
                        </form>
                    </section>
                </div>
            </div>
        </div>
    </div>
</section>
<section id="container">
    <div class="container" style="margin-top: -20px">
        <h2 style="margin-top: -20px"><small>/ Linhas de Pesquisa</small></h2>
        <div class="row">
            <div class="span12 featured-blocks">
                <div id="linhaspesquisa" class="carousel bttop">
                    <div class="carousel-wrapper">
                        <ul class="portfolio">
                            <li>
                                
                            </li>
                        </ul>
                    </div>
                </div>
                <ul class="thumbnails pull-center">
                    <li class="span3 thumbnail bg-color-orange-dark  fg-color-white">
                        <div class="image-icon"><i class="icon-hdd"></i></div>
                        <div class="caption fg-color-white">
                            <h3>BigData</h3>
                            <p>
                                Cras justo odio, dapibus ac facilisis in, egestas eget quam.
                                Donec id elit non mi porta gravida at eget metus.
                                Nullam id dolor id nibh ultricies vehicula.
                            </p>
                        </div>
                    </li>
                    <li class="span3 thumbnail bg-color-orange-dark fg-color-white">
                        <div class="image-icon"><i class="icon-magic"></i></div>
                        <div class="caption fg-color-white">
                            <h3>Business Intelligence</h3>
                            <p>
                                Cras justo odio, dapibus ac facilisis in, egestas eget quam.
                                Donec id elit non mi porta gravida at eget metus.
                                Nullam id dolor id nibh ultricies vehicula.
                            </p>
                        </div>
                    </li>
                    <li class="span3 thumbnail bg-color-orange-dark fg-color-white">
                        <div class="image-icon"><i class="icon-bar-chart"></i></div>
                        <div class="caption fg-color-white">
                            <h3>Data Mining</h3>
                            <p>
                                Cras justo odio, dapibus ac facilisis in, egestas eget quam.
                                Donec id elit non mi porta gravida at eget metus.
                                Nullam id dolor id nibh ultricies vehicula.
                            </p>
                        </div>
                    </li>
                    <li class="span3 thumbnail bg-color-orange-dark fg-color-white">
                        <div class="image-icon"><i class="icon-cogs"></i></div>
                        <div class="caption fg-color-white">
                            <h3>Software</h3>
                            <p>
                                Cras justo odio, dapibus ac facilisis in, egestas eget quam.
                                Donec id elit non mi porta gravida at eget metus.
                                Nullam id dolor id nibh ultricies vehicula.
                            </p>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
        <hr style="border-top: 1px solid #D6D3D1;border-bottom: 0px"/>
        <h2 style="margin-top: -45px"><small>/ Projetos</small></h2>
        <div class="row">
            <div class="span12">
                <div class="hero-unit">
                    <h4>Sistema de Apoio à Decisão para Gestão e Estruturação Organizacional da Secretaria de Inclusão Digital</h4>
                    <p style="width: 100%" align="justify"> Este projeto de pesquisa tem como objetivo principal o desenvolvimento de um sistema de apoio à decisão para gestão e estruturação
                        organizacional da Secretaria de Inclusão Digital (SID). O conjunto de informações a ser disponibilizado pelo sistema propicia um ambiente
                        favorável ao aperfeiçoamento da estrutura organizacional adotada pela SID. Esse ambiente é baseado na gestão por processos, na implantação
                        da prática de gestão por processos, no alinhamento entre novos fluxos, estrutura e estratégia, considerando periodicamente a necessidade 
                        de mudanças nas estratégias instituídas pelos usuários de níveis decisórios, no que concerne aos processos de inclusão digital. 
                        Além disso, o sistema contempla um conjunto de modelos matemáticos e de inteligência computacional que possibilitam a extração de padrões
                        e indicadores relacionados às ações de gestão no âmbito da SID</p>
                    <!--</p>     <a class="btn btn-welcome btn-large pull-right">Learn more</a>-->
                </div>
            </div>
        </div>
        <hr style="border-top: 1px solid #D6D3D1;border-bottom: 0px"/>
        <h2 style="margin-top: -45px"><small>/ Publicações</small></h2>
        <div class="row">
            <div class="span12">
                <blockquote>
                    <p>Est audiam urbanitas omittantur an, eum suas tota delectus an. Cu pro graece aliquando abhorreant. An usu sensibus disputationi consectetuer. His ridens tamquam prodesset id.</p>
                    <small>Something Important</small>
                </blockquote>
            </div>
        </div>
        <div class="row">
            <div class="span12"><h3>Our Work</h3></div>
            <div class="span12">
                <div id="our-projects" class="carousel bttop">
                    <div class="carousel-wrapper">
                        <ul class="portfolio">
                            <li>
                                <article>
                                    <div class="inner-image">
                                        <a href="example/view.jpg" data-rel="prettyPhoto">
                                            <img src="example/latest1.jpg" alt=""/>
                                            <span class="frame-overlay"></span>
                                        </a>
                                    </div>
                                    <div class="sliding">
                                        <div class="inner-text">
                                            <h4 class="title"><a href="./portfolio-single.html">Project title 1</a></h4>
                                        </div>
                                    </div>
                                </article>
                            </li>
                            <li>
                                <article>
                                    <div class="inner-image">
                                        <a href="example/view.jpg" data-rel="prettyPhoto">
                                            <img src="example/latest2.jpg" alt=""/>
                                            <span class="frame-overlay"></span>
                                        </a>
                                    </div>
                                    <div class="sliding">
                                        <div class="inner-text">
                                            <h4 class="title"><a href="./portfolio-single.html">Project title 2</a></h4>
                                        </div>
                                    </div>
                                </article>
                            </li>
                            <li>
                                <article>
                                    <div class="inner-image">
                                        <a href="example/view.jpg" data-rel="prettyPhoto">
                                            <img src="example/latest3.jpg" alt=""/>
                                            <span class="frame-overlay"></span>
                                        </a>
                                    </div>
                                    <div class="sliding">
                                        <div class="inner-text">
                                            <h4 class="title"><a href="./portfolio-single.html">Project title 3</a></h4>
                                        </div>
                                    </div>
                                </article>
                            </li>
                            <li>
                                <article>
                                    <div class="inner-image">
                                        <a href="example/view.jpg" data-rel="prettyPhoto">
                                            <img src="example/latest4.jpg" alt=""/>
                                            <span class="frame-overlay"></span>
                                        </a>
                                    </div>
                                    <div class="sliding">
                                        <div class="inner-text">
                                            <h4 class="title"><a href="./portfolio-single.html">Project title 4</a></h4>
                                        </div>
                                    </div>
                                </article>
                            </li>
                            <li>
                                <article>
                                    <div class="inner-image">
                                        <a href="example/view.jpg" data-rel="prettyPhoto">
                                            <img src="example/latest5.jpg" alt=""/>
                                            <span class="frame-overlay"></span>
                                        </a>
                                    </div>
                                    <div class="sliding">
                                        <div class="inner-text">
                                            <h4 class="title"><a href="./portfolio-single.html">Project title 5</a></h4>
                                        </div>
                                    </div>
                                </article>
                            </li>
                            <li>
                                <article>
                                    <div class="inner-image">
                                        <a href="example/view.jpg" data-rel="prettyPhoto">
                                            <img src="example/latest6.jpg" alt=""/>
                                            <span class="frame-overlay"></span>
                                        </a>
                                    </div>
                                    <div class="sliding">
                                        <div class="inner-text">
                                            <h4 class="title"><a href="./portfolio-single.html">Project title 6</a></h4>
                                        </div>
                                    </div>
                                </article>
                            </li>
                        </ul>
                    </div>
                </div>
                <script type="text/javascript">
                    $(document).ready(function(){
                        $('#our-projects').elastislide({
                            imageW : 270,
                            border : 0,
                            minItems : 1,
                            margin : 30
                        });
                    });
                </script>
            </div>
        </div>
        <div class="row">
            <div class="span12">
                <h3>Testimonials</h3>
            </div>
            <div class="span4">
                <p>
                    Suspendisse potenti. Suspendisse non sem lectus, eu sagittis diam. Nullam quis vestibulum augue.
                    Curabitur augue urna, viverra vel gravida et, aliquet eget erat.
                    Aliquam elit felis, pharetra id fringilla et, dignissim sed velit.
                </p>
            </div>
            <div class="span8">
                <!--testimonals-->
                <div id="testimonial" class="carousel bttop">
                    <div class="carousel-wrapper">
                        <ul class="testimonials">
                            <li>
                                <img src="example/testimonials1.jpg" alt="" />
                                <p>
                                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut in lacus rhoncus elit egestas luctus.
                                    Nullam at lectus augue. Ut tristique consectetur elit, sed tincidunt elit iaculis in. In hac habitasse platea dictumst.
                                    Curabitur condimentum justo sed urna porttitor aliquam.
                                </p>
                                <h4>Jhon Doe <small>Compani Inc.</small></h4>
                            </li>
                            <li>
                                <img src="example/testimonials2.jpg" alt="" />
                                <p>
                                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut in lacus rhoncus elit egestas luctus.
                                    Nullam at lectus augue. Ut tristique consectetur elit, sed tincidunt elit iaculis in. In hac habitasse platea dictumst.
                                    Curabitur condimentum justo sed urna porttitor aliquam.
                                </p>
                                <h4>Jhon Doe <small>Compani Inc.</small></h4>
                            </li>
                            <li>
                                <img src="example/testimonials3.jpg" alt="" />
                                <p>
                                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut in lacus rhoncus elit egestas luctus.
                                    Nullam at lectus augue. Ut tristique consectetur elit, sed tincidunt elit iaculis in. In hac habitasse platea dictumst.
                                    Curabitur condimentum justo sed urna porttitor aliquam.
                                </p>
                                <h4>Jhon Doe <small>Compani Inc.</small></h4>
                            </li>
                            <li>
                                <img src="example/testimonials4.jpg" alt="" />
                                <p>
                                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut in lacus rhoncus elit egestas luctus.
                                    Nullam at lectus augue. Ut tristique consectetur elit, sed tincidunt elit iaculis in. In hac habitasse platea dictumst.
                                    Curabitur condimentum justo sed urna porttitor aliquam.
                                </p>
                                <h4>Jhon Doe <small>Compani Inc.</small></h4>
                            </li>
                        </ul>
                    </div>
                </div>
                <script type="text/javascript">
                    $(document).ready(function(){
                        $('#testimonial').elastislide({
                            imageW  : 740,
                            margin  : 30
                        });
                    });
                </script>
            </div>
        </div>
    </div>
</section>
