<!--page header / breadcrumbs-->
<section class="breadcrumbs">
    <div class="container">
        <div class="page-header">
            <div class="row">
                <div class="span8">
                    <h1>Nossos Serviços <small></small></h1>
                    <div><a href="#" controller="index" action="inicio" onclick="Layout.go($(this))" >Home</a> &nbsp;&rsaquo;&nbsp; Serviços</div>
                </div>
                <div class="span4 hidden-phone">
                    <section class="search clearfix">
                        <form id="search" class="input-append">
                            <input class="span4" id="appendedInputButton" size="16" type="text" placeholder="Buscar por serviços" />
                            <input class="btn search-bt" type="submit" name="submit" value="" />
                        </form>
                    </section>
                </div>
            </div>
        </div>
    </div>
</section>
<section id="container">
    <div class="container" style="margin-top: -20px">

        <div class="row highlights">
            <div class="span3">
                <div class="hl-circle">
                    <a class="hl-icon3" href="#">service</a>
                </div>

                <div class="highlights-content clearfix">
                    <h5>Desenvolvimento de Sistemas Especializados</h5>

                    <p>
                        Lorem ipsum dolor sit amet, consectetuer
                        adipiscing elit, sed diam nonummy nibh euismod.
                    </p>

                    <a class="btn-small btn-hl" href="#">
                        <span>Saber mais</span>
                    </a><!-- button small end -->
                </div>
            </div>
            <div class="span3 ">
                <div class="hl-circle">
                    <a class="hl-icon2" href="#">service</a>
                </div>

                <div class="highlights-content clearfix">
                    <h5>Consultoria em Business Intelligence</h5>

                    <p>
                        Lorem ipsum dolor sit amet, consectetuer
                        adipiscing elit, sed diam nonummy nibh euismod.
                    </p>

                    <a class="btn-small btn-hl" href="#">
                        <span>Saber mais</span>
                    </a><!-- button small end -->
                </div>
            </div>
            <div class="span3">
                <div class="hl-circle">
                    <a class="hl-icon1" href="#">service</a>
                </div>

                <div class="highlights-content clearfix">
                    <h5>Consultoria em BigData / Sistema e Infraestrutura</h5>

                    <p>
                        Lorem ipsum dolor sit amet, consectetuer
                        adipiscing elit, sed diam nonummy nibh euismod.
                    </p>

                    <a class="btn-small btn-hl" href="#">
                        <span>Saber mais</span>
                    </a><!-- button small end -->
                </div>
            </div>
            <div class="span3 highlights">
                <div class="hl-circle">
                    <a class="hl-icon4" href="#">service</a>
                </div>

                <div class="highlights-content clearfix">
                     <h5>Consultoria em Análise e Mineração de Dados </h5>

                    <p>
                        Lorem ipsum dolor sit amet, consectetuer
                        adipiscing elit, sed diam nonummy nibh euismod.
                    </p>

                    <a class="btn-small btn-hl" href="#">
                        <span>Saber mais</span>
                    </a><!-- button small end -->
                </div>
            </div>
        </div>
    </div>
</section>


