-- MySQL Script generated by MySQL Workbench
-- 03/14/15 02:01:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `usu_perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usu_perfil` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `perfil` VARCHAR(100) NOT NULL,
  `excluido` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `gen_titulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gen_titulo` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(50) NOT NULL,
  `excluido` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gru_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gru_tipo` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(200) NOT NULL,
  `excluido` TINYINT UNSIGNED NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gru_grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gru_grupo` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_tipo` INT UNSIGNED NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `sigla` VARCHAR(50) NOT NULL,
  `logo` TEXT NOT NULL,
  `excluido` TINYINT UNSIGNED NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_instituicao_UNIQUE` (`id` ASC),
  INDEX `id_grupo_tipo_idx` (`id_tipo` ASC),
  CONSTRAINT `id_grupo_tipo`
    FOREIGN KEY (`id_tipo`)
    REFERENCES `gru_tipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `usu_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usu_usuario` (
  `id` INT UNSIGNED NOT NULL,
  `id_grupo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_titulo` INT UNSIGNED NOT NULL,
  `id_instituicao` INT UNSIGNED NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(200) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `excluido` TINYINT UNSIGNED NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `id_usuario_grupo`
    FOREIGN KEY (`id_grupo`)
    REFERENCES `usu_perfil` (`id`)
    ON DELETE NO ACTION
    ON UPDATE RESTRICT,
  CONSTRAINT `id_usuario_titulo`
    FOREIGN KEY (`id_titulo`)
    REFERENCES `gen_titulo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_usuario`
    FOREIGN KEY (`id_instituicao`)
    REFERENCES `gru_grupo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `usu_acao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usu_acao` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `modulo` VARCHAR(100) NOT NULL,
  `controller` VARCHAR(100) NOT NULL,
  `action` VARCHAR(100) NOT NULL,
  `alias_controller` VARCHAR(100) NOT NULL,
  `alias_action` VARCHAR(100) NOT NULL,
  `permissao` TINYINT UNSIGNED NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `usu_permissao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usu_permissao` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_perfil` INT UNSIGNED NOT NULL,
  `id_acao` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `id_perfil`, `id_acao`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `id_grupo_UNIQUE` (`id_perfil` ASC),
  UNIQUE INDEX `id_pagina_UNIQUE` (`id_acao` ASC),
  CONSTRAINT `id_permissao_grupo`
    FOREIGN KEY (`id_perfil`)
    REFERENCES `usu_perfil` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_permissao_acao`
    FOREIGN KEY (`id_acao`)
    REFERENCES `usu_acao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `log_registro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `log_registro` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_usuario` INT UNSIGNED NOT NULL,
  `id_permissao_acao` INT UNSIGNED NOT NULL,
  `descricao` TEXT NOT NULL,
  `data` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `id_registro_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `usu_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_registro_permissao_acao`
    FOREIGN KEY (`id_permissao_acao`)
    REFERENCES `usu_acao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `usu_vinculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usu_vinculo` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_usuario` INT UNSIGNED NOT NULL,
  `id_instituicao` INT UNSIGNED NOT NULL,
  `id_titulo` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `id_usuario`, `id_instituicao`, `id_titulo`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `id_vinculo_usuario_idx` (`id_usuario` ASC),
  INDEX `id_vinculo_titulo_idx` (`id_titulo` ASC),
  INDEX `id_vinculo_instituicao_idx` (`id_instituicao` ASC),
  CONSTRAINT `id_vinculo_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `usu_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_vinculo_instituicao`
    FOREIGN KEY (`id_instituicao`)
    REFERENCES `gru_grupo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_vinculo_titulo`
    FOREIGN KEY (`id_titulo`)
    REFERENCES `gen_titulo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pro_projeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pro_projeto` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_projeto` INT UNSIGNED NOT NULL,
  `id_responsavel` INT UNSIGNED NOT NULL,
  `id_coordenador` INT UNSIGNED NOT NULL,
  `id_fincanciador` INT UNSIGNED NOT NULL,
  `processo` TEXT NOT NULL,
  `resumo` TEXT NOT NULL,
  `edital` VARCHAR(200) NOT NULL,
  `inicio` DATE NOT NULL,
  `termino` DATE NOT NULL,
  `url` VARCHAR(200) NOT NULL,
  `apelido` VARCHAR(100) NOT NULL,
  `excluido` TINYINT UNSIGNED NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `id_projeto_usuario_idx` (`id_responsavel` ASC),
  INDEX `id_projeto_usuario_idx1` (`id_coordenador` ASC),
  INDEX `id_projeto_financiador_idx` (`id_fincanciador` ASC),
  INDEX `id_projeto_grupo_idx1` (`id_projeto` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `id_projeto_usuario_resp`
    FOREIGN KEY (`id_responsavel`)
    REFERENCES `usu_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_projeto_usuario_coord`
    FOREIGN KEY (`id_coordenador`)
    REFERENCES `usu_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_projeto_financiador`
    FOREIGN KEY (`id_fincanciador`)
    REFERENCES `gru_grupo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_projeto_grupo`
    FOREIGN KEY (`id_projeto`)
    REFERENCES `gru_grupo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gru_tipo_vinculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gru_tipo_vinculo` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(200) NOT NULL,
  `excluido` TINYINT UNSIGNED NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gru_vinculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gru_vinculo` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_grupo` INT UNSIGNED NOT NULL,
  `id_grupo_vinculado` INT UNSIGNED NOT NULL,
  `id_tipo` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `id_grupo`, `id_grupo_vinculado`, `id_tipo`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `id_vinculo_grupo_idx` (`id_grupo` ASC),
  INDEX `id_vinculo_grupo_vinculado_idx` (`id_grupo_vinculado` ASC),
  INDEX `id_tipo_idx` (`id_tipo` ASC),
  CONSTRAINT `id_vinculo_grupo`
    FOREIGN KEY (`id_grupo`)
    REFERENCES `gru_grupo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_vinculo_grupo_vinculado`
    FOREIGN KEY (`id_grupo_vinculado`)
    REFERENCES `gru_grupo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_tipo`
    FOREIGN KEY (`id_tipo`)
    REFERENCES `gru_tipo_vinculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pro_tarefa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pro_tarefa` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_vinculo_usuario` INT UNSIGNED NULL,
  `id_projeto` INT UNSIGNED NOT NULL,
  `titulo` VARCHAR(100) NOT NULL,
  `descricao` TEXT NOT NULL,
  `prioridade` ENUM('Alta', 'Normal', 'Baixa') NOT NULL,
  `deadline` DATETIME NOT NULL,
  `data_inicio` DATETIME NOT NULL,
  `status` ENUM('Em Análise', 'Aprovado', 'Recuzada', 'Pendente', 'Em Andamento', 'Realizada', 'Bloqueadas', 'Atrazada') NOT NULL,
  `id_tarefa` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `id_tarefa_tarefa_idx` (`id_tarefa` ASC),
  INDEX `id_tarefa_usuario_idx` (`id_vinculo_usuario` ASC),
  INDEX `id_tarefa_grupo_idx` (`id_projeto` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `id_tarefa_usuario`
    FOREIGN KEY (`id_vinculo_usuario`)
    REFERENCES `usu_vinculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_tarefa_tarefa`
    FOREIGN KEY (`id_tarefa`)
    REFERENCES `pro_tarefa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_tarefa_grupo`
    FOREIGN KEY (`id_projeto`)
    REFERENCES `gru_grupo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gen_post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gen_post` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_usuaro` INT UNSIGNED NULL,
  `id_grupo` INT UNSIGNED NULL,
  `id_tarefa` INT UNSIGNED NULL,
  `comentario` TEXT NOT NULL,
  `data` DATETIME NOT NULL,
  `id_resposta` TINYINT UNSIGNED NULL,
  `excluido` TINYINT UNSIGNED NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `id_post_usuario_idx` (`id_usuaro` ASC),
  INDEX `id_post_grupo_idx` (`id_grupo` ASC),
  INDEX `id_post_tarefa_idx` (`id_tarefa` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `id_post_usuario`
    FOREIGN KEY (`id_usuaro`)
    REFERENCES `usu_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_post_grupo`
    FOREIGN KEY (`id_grupo`)
    REFERENCES `gru_grupo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_post_post`
    FOREIGN KEY (`id`)
    REFERENCES `gen_post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_post_tarefa`
    FOREIGN KEY (`id_tarefa`)
    REFERENCES `pro_tarefa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gen_anexo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gen_anexo` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_tarefa` INT UNSIGNED NULL,
  `id_post` INT UNSIGNED NULL,
  `id_grupo` INT UNSIGNED NULL,
  `localizaca` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(200) NOT NULL,
  `excluido` TINYINT UNSIGNED NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `id_anexo_tarefa_idx` (`id_tarefa` ASC),
  INDEX `id_anexo_post_idx` (`id_post` ASC),
  INDEX `id_anexo_grupo_idx` (`id_grupo` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `id_anexo_tarefa`
    FOREIGN KEY (`id_tarefa`)
    REFERENCES `pro_tarefa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_anexo_post`
    FOREIGN KEY (`id_post`)
    REFERENCES `gen_post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_anexo_grupo`
    FOREIGN KEY (`id_grupo`)
    REFERENCES `gru_grupo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Placeholder table for view `view_perfil_acao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `view_perfil_acao` (`id_perfil` INT, `acao` INT, `alias_controller` INT, `alias_action` INT, `permissao` INT);

-- -----------------------------------------------------
-- View `view_perfil_acao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `view_perfil_acao`;
CREATE  OR REPLACE VIEW `view_perfil_acao` AS
SELECT
   `permissao`.`id_perfil` AS `id_perfil`,concat_ws('/',`acao`.`modulo`,
   `acao`.`controller`,
   `acao`.`action`) AS `acao`,
   `acao`.`alias_controller` AS `alias_controller`,
   `acao`.`alias_action` AS `alias_action`,
   `acao`.`permissao` AS `permissao`
FROM (`usu_permissao` `permissao` join `usu_acao` `acao` on((`permissao`.`id_acao` = `acao`.`id`))) 
;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
