INSERT INTO `mydb`.`estado`(`id`,`nome`,`sigla`)VALUES(01,'amazonas','am');
INSERT INTO `mydb`.`estado`(`id`,`nome`,`sigla`)VALUES(02,'amapá','ap');
INSERT INTO `mydb`.`estado`(`id`,`nome`,`sigla`)VALUES(03,'bahia','ba');
INSERT INTO `mydb`.`estado`(`id`,`nome`,`sigla`)VALUES(04,'ceará','ce');
INSERT INTO `mydb`.`estado`(`id`,`nome`,`sigla`)VALUES(05,'distrito federal','df');
INSERT INTO `mydb`.`estado`(`id`,`nome`,`sigla`)VALUES(06,'espírito santo','es');
INSERT INTO `mydb`.`estado`(`id`,`nome`,`sigla`)VALUES(07,'maranhão','ma');
INSERT INTO `mydb`.`estado`(`id`,`nome`,`sigla`)VALUES(08,'minas gerais','mg');
INSERT INTO `mydb`.`estado`(`id`,`nome`,`sigla`)VALUES(09,'pará','pa');
INSERT INTO `mydb`.`estado`(`id`,`nome`,`sigla`)VALUES(10,'paraíba','pb');
INSERT INTO `mydb`.`estado`(`id`,`nome`,`sigla`)VALUES(11,'pernambuco','pe');
INSERT INTO `mydb`.`estado`(`id`,`nome`,`sigla`)VALUES(12,'piauí','pi');
INSERT INTO `mydb`.`estado`(`id`,`nome`,`sigla`)VALUES(13,'paraná','pr');
INSERT INTO `mydb`.`estado`(`id`,`nome`,`sigla`)VALUES(14,'rio de janeiro','rj');
INSERT INTO `mydb`.`estado`(`id`,`nome`,`sigla`)VALUES(15,'rio grande do norte','rn');
INSERT INTO `mydb`.`estado`(`id`,`nome`,`sigla`)VALUES(16,'rio grande do sul','rs');
INSERT INTO `mydb`.`estado`(`id`,`nome`,`sigla`)VALUES(17,'santa catarina','sc');
INSERT INTO `mydb`.`estado`(`id`,`nome`,`sigla`)VALUES(18,'são paulo','sp');