INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(01,01,'Coari');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(02,01,'Manacapuru');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(03,01,'Manaquiri');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(04,02,'Serra do Navio');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(05,03,'Guanambi');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(06,03,'Itaberaba');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(07,03,'Itabuna');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(08,03,'Juazeiro');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(09,03,'Lauro de Freitas');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(10,03,'Nilo Peçanha');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(11,03,'Piraí do Norte');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(12,03,'Uruçucá');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(13,03,'Vitória da Conquista');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(14,04,'Araripe');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(15,04,'Barreira');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(16,04,'Brejo Santo');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(17,04,'Jaguaruana');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(18,04,'Maracanaú');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(19,04,'Milhã');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(20,04,'Quixeramobim');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(21,04,'São Gonçalo do Amarante');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(22,04,'Varjota');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(23,04,'Viçosa do Ceará');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(24,05,'Estrutural');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(25,06,'Cariacica');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(26,07,'São José do Ribamar');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(27,08,'Nepomuceno');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(28,08,'Pimenta');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(29,08,'Rio Acima');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(30,09,'Conceição do Araguaia');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(31,09,'Curuçá');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(32,09,'Goianésia do Pará');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(33,09,'Itaituba');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(34,09,'Marituba');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(35,09,'Paragominas');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(36,09,'Trairão');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(37,09,'Tucuruí');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(38,09,'Uruará');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(39,10,'Cabaceiras');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(40,10,'Cachoeira dos Índios');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(41,10,'Esperança');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(42,10,'Itaporanga');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(43,10,'Lagoa Seca');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(44,10,'Nova Floresta');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(45,10,'Pocinhos');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(46,10,'Queimadas');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(47,10,'São João do Rio do Peixe');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(48,11,'Bodocó');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(49,11,'Casinhas');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(50,11,'Correntes');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(51,12,'Inhuma');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(52,12,'Regeneração');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(53,12,'São José do Divino');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(54,13,'Assis Chateaubriand');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(55,13,'Bandeirantes');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(56,13,'Ibiporã');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(57,13,'Palmas');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(58,13,'Quatro Barras');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(59,13,'Santa Cecília do Pavão');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(60,13,'São Miguel do Iguaçu');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(61,13,'Toledo');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(62,14,'Engenheiro Paulo de Frontin');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(63,14,'Maricá');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(64,14,'São José do Vale do Rio Preto');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(65,15,'São João do Sabugi');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(66,16,'Candelária');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(67,16,'Jari');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(68,16,'Não-me-toque');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(69,16,'Nova Bassano');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(70,16,'Santo Ângelo');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(71,16,'São Miguel das Missões');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(72,17,'Joaçaba');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(73,18,'Casa Branca');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(74,18,'Descalvado');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(75,18,'Guararapes');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(76,18,'Lourdes');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(77,18,'Penápolis');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(78,18,'Presidente Epitácio');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(79,18,'Santa Gertrudes');
INSERT INTO `mcsidcb`.`cidade`(`id`,`estado_id`,`nome`)VALUES(80,18,'Socorro');