<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="pt"> <!--<![endif]-->
    <head>
        <meta http-equiv="Content-Type" content ="text/html; charset=utf-8" />
        <meta name="viewport" content="width=100%; initial-scale=1; maximum-scale=1; minimum-scale=1; user-scalable=no;" />
        <!--<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">-->
        <link async rel="shortcut icon" href="./public/images/fav.ico"/>
        <title>::LINC - Laboratório de Inteligência Computacional::</title>
        <link async href="./public/css/bootstrap.min.css" type="text/css" rel="stylesheet"/>
        <link  async href="./public/css/style.css" type="text/css" rel="stylesheet"/>
        <link async href="./public/css/prettyPhoto.css" type="text/css" rel="stylesheet"/>
        <!--<link  href="./public/css/font-icomoon.css" type="text/css" rel="stylesheet"/>-->
        <link  href="./public/css/font-awesome.css" type="text/css" rel="stylesheet"/>
        <!--[if IE 7]>
        <link rel="stylesheet" href="assets/./public/css/font-awesome-ie7.css"/>
        <![endif]-->
        <!--[if lt IE 9]>
        <script type="text/javascript" src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
    </head>
    <body>
        <!--top menu-->
        <section id="top-menu">
            <div class="container">
                <div class="row">
                </div>
            </div>
        </section>
        <!--header-->
        <header id="header">
            <div class="container">
                <div class="row header-top">
                    <div class="span5 logo">
                        <a class="logo-img" href="javascript:;" controller="index" action="inicio" onclick="Layout.go($(this))"title="responsive template">
                            
                            <img src="./public/images/logo.png" width="120" alt="Tabulate"></a>
                        <p class="tagline" style="margin-top: 35px;">Laboratório de Inteligência Computacional e Pesquisa Operacional.</p>
                    </div>
                    <div class="span7 social-container" >
                        <p class="phone hidden-phone"><i class="icon-envelope"></i> linc.ufpa@gmail.com</p>
                        <p class="phone hidden-phone"> +55 91 3201-7870</p>
                        <div class="top-social">
                            <a data-original-title="Facebook" target="_blank" rel="tooltip" data-placement="top" class="facebook"
                               href="http://www.facebook.com/linc.ufpa"></a>
                          <!--  <a data-original-title="Twitter" target="_blank"  rel="tooltip" data-placement="top" class="twitter2"
                               href="http://www.twitter.com"></a> -->
                        </div>
                    </div>
                </div>
                <div class="row header-nav" style="margin-top: -20px;">
                    <div class="span12">
                        <nav id="menu" class="clearfix">
                            <ul>
                                <li class="current"><a href="javascript:;" controller="index" action="inicio" onclick="Layout.go($(this))">
                                        <span class="name" >Home</span>
                                    </a>
                                </li>
                                <li><a href="javascript:;" controller="index" action="pesquisa" onclick="Layout.go($(this))"><span class="name">Pesquisa</span></a>
                                    <ul>
                                        <li><a href="javascript:;">Linhas de Pesquisa</a></li>
                                        <li><a href="javascript:;">Projetos</a></li>
                                        <li><a href="javascript:;">Publicações</a></li>
                                       <!-- <li><a href="javascript:;">Áreas de Interesse</a></li>
                                        <li><a href="javascript:;">Programa de Afiliados</a> 
                                            <ul>
                                                <li><a href="javascript:;">Acesso à visualização de informações do projeto</a></li>
                                                <li><a href="javascript:;">Acompanhamento de atividades</a></li>
                                            </ul>
                                        </li>-->
                                    </ul>
                                </li>
                                <li><a href="javascript:;" controller="index" action="media" onclick="Layout.go($(this))"><span class="name">Mídia</span></a>
                                    <ul>
                                        <li><a href="javascript:;">Códigos/Apps</a></li>
                                     <!--   <li><a href="javascript:;">Galeria</a></li>
                                        <li><a href="javascript:;">Videos</a></li>
                                        <li><a href="javascript:;">Livros</a></li>-->
                                        <li><a href="javascript:;">Apresentações/MISC</a></li> 
                                    </ul>
                                </li>
                                <li><a href="javascript:;" controller="index" action="noticias" onclick="Layout.go($(this))"><span class="name">Notícias</span></a></li>
                                <li><a href="javascript:;" controller="index" action="equipe" onclick="Layout.go($(this))"><span class="name" >Equipe</span></a></li>
                            <!--    <li><a href="javascript:;" controller="index" action="servicos" onclick="Layout.go($(this))"><span class="name">Serviços</span></a></li> -->
                                <li><a href="javascript:;" controller="index" action="contato" onclick="Layout.go($(this))"><span class="name">Contato</span></a></li>
                            </ul>
                        </nav>
                      
                    </div>
                </div>
            </div>
        </header>
        <div id="erroloading" class="alert alert-danger" style="display: none;">
            <a class="close" onclick="$('#erroloading').hide();">×</a>
        </div>
        <div id="main">

        </div>
        <!--footer-->
        <footer id="footer">
            <div class="container">
                <div class="row">
                    <div class="span4">
                        <p><img src="./public/images/logo.png" width="100" alt=""></p>
                        <address>
                            <p><i class="icon-map-marker"></i> Universidade Federal do Pará - Campus profissional</p>
                            <p><i class="fa fa-phone"></i> +55 (91) 3201-7870</p>
                            <p><i class="icon-envelope"></i> <a href="mailto:#">linc.ufpa@gmail.com</a></p>
                        </address>
                    </div>
                    <div class="span8">
                        <div class="row">
                            <div class="span8"></div>
                            <div class="span8">
                            </div>
                        </div>
                    </div>
                    <!--
                    <div class="span4">
<!--                        <p class="heading">Sobre nós</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris porta imperdiet augue/<p>
                        <p class="heading">Assinar</p>
                        <p>Mantenha-se atualizado com as nossas novidades. Seu e-mail é seguro com a gente!</p>
                        <div class="input-append">
                            <input type="text" placeholder="Digite seu e-mail" class="span2"/>
                            <button type="button" class="btn btn-inverse">Assinar!</button>
                        </div>
                    </div> -->
                    <div class="span4">
                        <p class="heading">:: LINC-UFPa ::</p>
                        <ul class="footer-navigate">
                            <li><a href="javascript:;" controller="index" action="inicio" onclick="Layout.go($(this))">Home</a></li>
                            <li><a href="javascript:;" controller="index" action="pesquisa" onclick="Layout.go($(this))">Pesquisa</a></li>
                            <li><a href="javascript:;" controller="index" action="media" onclick="Layout.go($(this))">Mídia</a></li>
                            <li><a href="javascript:;" controller="index" action="noticias" onclick="Layout.go($(this))">Notícias</a></li>
                            <li><a href="javascript:;" controller="index" action="equipe" onclick="Layout.go($(this))">Equipe</a></li>
                            <li><a href="javascript:;" controller="index" action="contato" onclick="Layout.go($(this))">Contato</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
        <!--footer menu-->
        <section id="footer-menu">
            <div class="container">
                <div class="row">
                    <div class="span4">
                        <p class="copyright">LINC-UFPa &copy; Copyright 2014.</p>
                    </div>
                    <div class="span8 hidden-phone">
                        <ul class="pull-right">
                            <li><a href="#">Políticas de utilização</a></li>
                            <li><a href="javascript:;" controller="index" action="mapa" onclick="Layout.go($(this))">Mapa do site</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </section>
        <script type="text/javascript" src="./public/js/jquery.min.js"></script>
        <script>
                    
            var Layout = {
                $path: localStorage.getItem('lincssite_path'),
                $action: localStorage.getItem('lincssite_action'),
                $container:$("#main"),
                $erromsg:$("#erroloading"),
                $pagedefault:"./index/inicio",
                $avatar:null,
                        
                init:function(){
                    try{
                        Layout.$erromsg.hide();
                        if(Layout.$action== null){
                            $('#menu > ul').find('li:first').addClass("active");
                        }
                        //
                        Layout.$path = (Layout.$path == null) ? Layout.$pagedefault : Layout.$path;
                        Layout.$container.html("<p><progress></progress></p>").load(Layout.$path, 
                        function(response, status, xhr){
                            if (status == "error") {
                                var msg = "Desculpe-nos, ocorreu o seguinte erro : "+ xhr.status + " - " + xhr.statusText;
                                Layout.$erromsg.html('<a class="close" onclick="$(\'#erroloading\').hide();">×</a>'+msg);
                                Layout.$erromsg.show('slide');
                                Layout.$container.html('');
                            }
                        });
                        //
                    }catch(e){
                        console.log(e);
                    }
                },
                go:function(item){
                    try{
                        Layout.$erromsg.hide();
                        $('.current').each(function(){
                            $(this).removeClass("current");
                        });
                        //removeActive();
                        Layout.$path = './';
                        var controller = item.attr('controller');
                        var action = item.attr('action');
                        var _function = item.attr('function');
                        var param = item.attr('param');
                        if(controller!=undefined)
                        {
                            Layout.$path+=controller;
                        }
                        if(action!=undefined)
                        {
                            Layout.$path+='/'+action;
                        }
                        if(_function!=undefined)
                        {
                            Layout.$path+='/function/'+_function;
                        }
                        localStorage.setItem('lincssite_path', Layout.$path);
                        localStorage.setItem('lincssite_action', action);
                        //
//                        if( localStorage.getItem(action)==null){
                            Layout.$container.html('<section id="container"><div class="container"><div class="row"><div class="span12"><h2>Carregando...</h2></div></div></div></section>').load(Layout.$path, function(response, status, xhr) {
                                localStorage.setItem(action, response);
                                if (status == "error") {
                                    var msg = "Desculpe-nos, ocorreu o seguinte erro : "+ xhr.status + " - " + xhr.statusText;
                                    Layout.$erromsg.html('<a class="close" onclick="$(\'#erroloading\').hide();">×</a>'+msg);
                                    Layout.$erromsg.show();
                                    
                                    Layout.$container.html('');
                                }
                            });
//                        }else{
//                            Layout.$container.html(localStorage.getItem(action));
//                        }
                        item.parent().addClass('current');
                    }catch(e){
                        console.log(e);
                    }
                },
                load:function(path,name,type,sync,addheader){
                    try{
                        var tag;
                        switch(type){
                            case 'style':
                                tag = document.createElement('style');
                                break;
                            case 'script':
                                tag = document.createElement('script');
                                break;
                            default:
                                tag = document.createElement('script');
                        };
                        tag.setAttribute("name",name);
                        if(!Layout.exist(path)){
                            if(localStorage.getItem(name)==null){
                                var file = new XMLHttpRequest();
                                file.open("GET", path, sync);
                                file.onreadystatechange = function() {
                                    if (file.readyState === 4) {  // Makes sure the document is ready to parse.
                                        if (file.status === 200) {  // Makes sure it's found the file.
                                            allText = file.responseText; 
                                            localStorage.setItem(name,allText);
                                            tag.textContent = localStorage.getItem(name);
                                            if(addheader){
                                                document.head.appendChild(tag);
                                            }
                                        }
                                    }
                                }
                                file.send(null);
                            }else{
                                tag.textContent = localStorage.getItem(name);
                                document.head.appendChild(tag);
                            }
                        }
                    }catch(e){
                        alert(e);
                    }
                },
                extrairArquivo:function(Caminho){
                    Caminho = Caminho.replace(/\\/g, "/");
                    var Arquivo = Caminho.substring(Caminho.lastIndexOf('/') + 1);
                    return Arquivo;
                },
                exist:function(url){
                    var scriptExiste = false;
                    var scripts = document.getElementsByTagName("head")[0].getElementsByTagName("script");
                    var i;
                    for(i = 0; i < scripts.length; i++) {
                        var name = scripts[i].getAttribute('name');
                        if(name==null){
                            name = Layout.extrairArquivo(scripts[i].src);
                        }
                        if(name == Layout.extrairArquivo(url)) {
                            scriptExiste = true;
                        }
                    }
                    return scriptExiste;
                }
            };
                   
            $(document).ready(function(){
                Layout.load("./public/js/jquery.min.js", "jquery.min.js", "script", false, false);
                Layout.load("./public/js/bootstrap.min.js", "bootstrap.min.js", "script", true, true);
                Layout.load("./public/js/jquery.easing.1.3.js", "jquery.easing.1.3.js", "script", true, true);
                Layout.load("./public/js/jquery.quicksand.js", "jquery.quicksand.js", "script", true, true);
                Layout.load("./public/js/superfish.js", "superfish.js", "script", true, true);
                Layout.load("./public/js/hoverIntent.js", "hoverIntent.js", "script", true, true);
                Layout.load("./public/js/jquery.flexslider.js", "jquery.flexslider.js", "script", true, true);
                Layout.load("./public/js/jflickrfeed.min.js", "jflickrfeed.min.js", "script", true, true);
                Layout.load("./public/js/jquery.prettyPhoto.js", "jquery.prettyPhoto.js", "script", true, true);
                Layout.load("./public/js/jquery.elastislide.js", "jquery.elastislide.js", "script", true, true);
                Layout.load("./public/js/jquery.tweet.js", "jquery.tweet.js", "script", true, true);
                Layout.load("./public/js/smoothscroll.js", "smoothscroll.js", "script", true, true);
                Layout.load("./public/js/jquery.ui.totop.js", "jquery.ui.totop.js", "script", true, true);
                Layout.load("./public/js/main.js", "main.js", "script", true, true);
                Layout.load("./public/js/ajax-mail.js", "ajax-mail.js", "script", true, true);
                Layout.init();
            });
        </script>
    </body>
</html>
